name: Unit Test
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm i
      - name: test
        run: npm run test
      - name: run coverage
        run: npm run coverage
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          vite-config-path: ./vite.config.ts
