name: Deployment
on:
  push:
    branches:
      - '**'

jobs:
  #   test:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v3
  #       - name: Install dependecies
  #         run: npm i
  #       - name: test
  #         run: npm run test
  #       - name: run coverage
  #         run: npm run coverage
  #       - name: Report Coverage
  #         if: always()
  #         uses: davelosert/vitest-coverage-report-action@v1
  #         with:
  #           vite-config-path: ./vite.config.ts

  #   cypress:
  #     runs-on: ubuntu-latest
  #     needs: test
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v3
  #       - name: Cypress run
  #         uses: cypress-io/github-action@v5
  #         with:
  #           start: npm run serve
  #           wait-on: 'http://ip6-localhost:5173/' # this has been changed when the default runner on git hub changed to node 18
  #           record: false
  #         env:
  #           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #   sonarcloud:
  #     needs: cypress
  #     runs-on: ubuntu-latest
  #     permissions: read-all
  #     steps:
  #       - name: checkout
  #         uses: actions/checkout@v3
  #         with:
  #           fetch-depth: 0

  #       - name: install dependencies
  #         run: npm i

  #       - name: run test coverage
  #         run: npm run coverage
  #       #   - name: pull sonarqube image
  #       #     run: docker pull sonarqube
  #       - name: SonarCloud Scan
  #         uses: SonarSource/sonarcloud-github-action@master
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release-to-github:
    name: releease to github
    runs-on: ubuntu-latest
    # needs: sonarcloud
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: create tag
        id: create_tag
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          git tag -a "$TAG_NAME" -m "Release"
          git push --tags
          git pull origin
      - name: check the tag name
        run: echo $TAG_NAME
      - uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: $TAG_NAME
