name: Roll back

on:
  push:
    branches:
      - '**'

jobs:
  get-last-working-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for the keyword in the commit message
        run: |
          if [[ $(git log --format=%B -n 1 $GITHUB_SHA) == *"rollback"* ]]; then
            echo "Keyword found in commit message. Proceeding with the workflow..."
          else
            echo "No keyword found in commit message. Skipping the workflow."
            exit 1
          fi

  run-the-deployment-flow:
    runs-on: ubuntu-latest
    needs: get-last-working-version

    steps:
      - name: Checkout respository
        uses: actions/checkout@v3
      - name: Gets the version Number
        run: |
          commit_message=$(git log --format=%s -n 1)
          echo "LATEST_STABLE_VERSION=$(echo "$commit_message" | grep -o '\b[v][[:alnum:]]*' | head -n 1)" >> $GITHUB_ENV

      - name: Checks the variable
        run: |
          echo ${{env.LATEST_STABLE_VERSION}}
